sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    bucket-name: sky-web-learn
    #前段已经加上了https://
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: xCJcvszlrQCRpZ11Dj6OFc84GvHzve
    access-key-id: LTAI5t5yuZLEHWVvapumgu8M
